title: Oh Nice One
author: albytseng
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This be an awesome site description as you had requested so read this at your own leisure, thank you very much.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
